* got rid of screenshot dependency to remove nasty dep overrides. Instead extracted relevant code to do screenshot ourselves.
* reverted flutter downgrade

Still getting a new error when trying to do a screenshot:

```
  DriverError: Failed to fulfill SetFrameSync due to remote
  Original error: Bad state: StreamSink is closed
```